### ISSUE TITLE
watchman.checks.storage should write bytes to test-file on Py3

### ISSUE THREAD

**Issue by saily** [mwarkentin/django-watchman#101]
Hi, i'm giving `django-minio-storage` a try and got an exception when storage-check is executed. I'm running Python 3.4.5 and Django 1.10.6. 

    Traceback (most recent call last):
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/watchman/decorators.py", line 17, in wrapped
        response = func(*args, **kwargs)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/watchman/checks.py", line 63, in _check_storage
        path = default_storage.save(filename, ContentFile(content))
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/django/core/files/storage.py", line 54, in save
        return self._save(name, content)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/minio_storage/storage.py", line 77, in _save
        content_type)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/minio/api.py", line 894, in put_object
        current_data, metadata=metadata)
      File "/Users/daniel/Workspace/my_project/lib/python3.4/site-packages/minio/api.py", line 1557, in _do_put_object
        raise ValueError('Input data must be bytes type')
    ValueError: Input data must be bytes type

I was able to fix it by using a `byte` instead of `str` writing to the dummy file. This should basically work on Python 2.7 - i'd file a PR later.

**Comment by mwarkentin** [comment]
@saily Thanks for the report - I'm not too familiar w/ Python 3 yet (we're starting to begin the migration though). Happy to get a fix in if you can open a PR though. :)

**Comment by mwarkentin** [comment]
If you were able to add a test which could confirm that it works on both python 2.7 and 3.x that would be super helpful!

**Comment by saily** [comment]
Travis will hopefully do so :-)

**Comment by saily** [comment]
@mwarkentin see: https://travis-ci.org/mwarkentin/django-watchman/builds/215590048
