### ISSUE TITLE
Nose is unsupported and doesn't support python3.10

### ISSUE THREAD

**Issue by mwarkentin** [mwarkentin/django-watchman#175]
> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

Figure out if we should switch to pytest, or just use basic `unittest` functionality for testing. For now we will exclude python 3.10 from test runs.

* https://github.com/mwarkentin/django-watchman/runs/4609329660?check_suite_focus=true
* https://docs.pytest.org/en/6.2.x/nose.html
* https://github.com/datalad/datalad/issues/6225

Traceback:

```
2021-12-22T16:39:45.2849112Z Traceback (most recent call last):
2021-12-22T16:39:45.2852381Z   File "/home/runner/work/django-watchman/django-watchman/runtests.py", line 54, in <module>
2021-12-22T16:39:45.2853741Z     run_tests(*sys.argv[1:])
2021-12-22T16:39:45.2855126Z   File "/home/runner/work/django-watchman/django-watchman/runtests.py", line 47, in run_tests
2021-12-22T16:39:45.2856199Z     failures = test_runner.run_tests(test_args)
2021-12-22T16:39:45.2857709Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/django_nose/runner.py", line 308, in run_tests
2021-12-22T16:39:45.2858785Z     result = self.run_suite(nose_argv)
2021-12-22T16:39:45.2860162Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/django_nose/runner.py", line 244, in run_suite
2021-12-22T16:39:45.2861339Z     nose.core.TestProgram(argv=nose_argv, exit=False,
2021-12-22T16:39:45.2862765Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
2021-12-22T16:39:45.2863837Z     unittest.TestProgram.__init__(
2021-12-22T16:39:45.2864856Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/unittest/main.py", line 100, in __init__
2021-12-22T16:39:45.2866115Z     self.parseArgs(argv)
2021-12-22T16:39:45.2867481Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
2021-12-22T16:39:45.2868518Z     self.createTests()
2021-12-22T16:39:45.2869837Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
2021-12-22T16:39:45.2871732Z     self.test = self.testLoader.loadTestsFromNames(self.testNames)
2021-12-22T16:39:45.2873972Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
2021-12-22T16:39:45.2875519Z     return unittest.TestLoader.loadTestsFromNames(self, names, module)
2021-12-22T16:39:45.2877048Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
2021-12-22T16:39:45.2878271Z     suites = [self.loadTestsFromName(name, module) for name in names]
2021-12-22T16:39:45.2879466Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
2021-12-22T16:39:45.2880596Z     suites = [self.loadTestsFromName(name, module) for name in names]
2021-12-22T16:39:45.2882226Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
2021-12-22T16:39:45.2883442Z     return self.loadTestsFromModule(
2021-12-22T16:39:45.2884986Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
2021-12-22T16:39:45.2886254Z     tests.extend(self.loadTestsFromDir(module_path))
2021-12-22T16:39:45.2887800Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/loader.py", line 183, in loadTestsFromDir
2021-12-22T16:39:45.2888971Z     yield self.loadTestsFromName(
2021-12-22T16:39:45.2890434Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
2021-12-22T16:39:45.2891644Z     return self.loadTestsFromModule(
2021-12-22T16:39:45.2893188Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
2021-12-22T16:39:45.2894825Z     return self.suiteClass(ContextList(tests, context=module))
2021-12-22T16:39:45.2896319Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
2021-12-22T16:39:45.2897372Z     return self.makeSuite(tests, context, **kw)
2021-12-22T16:39:45.2898727Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
2021-12-22T16:39:45.2899732Z     suite = self.suiteClass(
2021-12-22T16:39:45.2901001Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
2021-12-22T16:39:45.2902038Z     super(ContextSuite, self).__init__(tests)
2021-12-22T16:39:45.2903363Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
2021-12-22T16:39:45.2904347Z     super(LazySuite, self).__init__()
2021-12-22T16:39:45.2905299Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/unittest/suite.py", line 22, in __init__
2021-12-22T16:39:45.2906131Z     self._tests = []
2021-12-22T16:39:45.2907362Z   File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
2021-12-22T16:39:45.2908522Z     if isinstance(tests, collections.Callable) and not is_suite:
2021-12-22T16:39:45.2909740Z AttributeError: module 'collections' has no attribute 'Callable'
```

**Comment by mwarkentin** [comment]
Should be fixed by #206
